export default {
  '@odata.context': "http://aisrvw10saas01/sem-webapi/Spem/V1/$metadata#Sites('AGSite2018_1_Oracle')/Plants('AGPlant2018_2_Oracle')/Applications",
  value: [
    {
      Id: 'Sppid',
      ConcurrencyToken: '5248052767691743394',
      DataBaseType: 'Oracle',
      SiteIniFileNamePath: '\\\\ISRVSORA12SPEM\\AppOra12\\Alon Sites\\AGSite2018_1_Oracle',
      ApplicationType: 'Sppid',
      OracleAlias: 'SPEM12DEV',
      OracleSystemUser: 'system',
      OracleSystemPassword: 'H4#######5######R#######u#######d#######f#######o#######h#######',
      SchemaOracleUserName: 'AGPlant2018_2_Oraclepid',
      SchemaOraclePassword: 'CJ4f#####S;o#####obh#####d5s#####qbl#####wRg#####5u#####D3d#####',
      DataDictOracleUserName: 'AGPlant2018_2_Oraclepidd',
      DataDictOraclePassword: 'CJ4f#####S;o#####obh#####d5s#####qbl#####wRg#####5ug####D3d#####',
      'Items@odata.context': "http://aisrvw10saas01/sem-webapi/Spem/V1/$metadata#Sites('AGSite2018_1_Oracle')/Plants('AGPlant2018_2_Oracle')/Applications('Sppid')/Items",
      Items: [
        {
          Id: 'AreaBreak',
          ConcurrencyToken: '5248052767796275222',
          Name: 'AreaBreak',
          ValidationProgramId: '',
          Description: 'Area Break',
          EntityDescription: 'Area Break',
        },
        {
          Id: 'AreaBreakAttribute',
          ConcurrencyToken: '5248052767796275222',
          Name: 'AreaBreakAttribute',
          ValidationProgramId: '',
          Description: 'Area Break Attribute',
          EntityDescription: 'Area Break Attribute',
        },
        {
          Id: 'BoundedShape',
          ConcurrencyToken: '5248052767796275222',
          Name: 'BoundedShape',
          ValidationProgramId: '',
          Description: 'Bounded Shape',
          EntityDescription: 'Bounded Shape',
        },
        {
          Id: 'BoundedShapeVertex',
          ConcurrencyToken: '5248052767796275222',
          Name: 'BoundedShapeVertex',
          ValidationProgramId: '',
          Description: 'Bounded Shape Vertex',
          EntityDescription: 'Bounded Shape Vertex',
        },
        {
          Id: 'Case',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Case',
          ValidationProgramId: '',
          Description: 'Case',
          EntityDescription: 'Case',
        },
        {
          Id: 'CaseControl',
          ConcurrencyToken: '5248052767796275222',
          Name: 'CaseControl',
          ValidationProgramId: '',
          Description: 'Case Control',
          EntityDescription: 'Case Control',
        },
        {
          Id: 'CaseProcess',
          ConcurrencyToken: '5248052767796275222',
          Name: 'CaseProcess',
          ValidationProgramId: '',
          Description: 'Case Process',
          EntityDescription: 'Case Process',
        },
        {
          Id: 'Connector',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Connector',
          ValidationProgramId: '',
          Description: 'Connector',
          EntityDescription: 'Connector',
        },
        {
          Id: 'ConnectorVertex',
          ConcurrencyToken: '5248052767796275222',
          Name: 'ConnectorVertex',
          ValidationProgramId: '',
          Description: 'Connector Vertex',
          EntityDescription: 'Connector Vertex',
        },
        {
          Id: 'Drawing',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Drawing',
          ValidationProgramId: '',
          Description: 'Drawing',
          EntityDescription: 'Drawing',
        },
        {
          Id: 'DrawingProject',
          ConcurrencyToken: '5248052767796275222',
          Name: 'DrawingProject',
          ValidationProgramId: '',
          Description: 'Drawing Project',
          EntityDescription: 'Drawing Project',
        },
        {
          Id: 'DrawingStorage',
          ConcurrencyToken: '5248052767796275222',
          Name: 'DrawingStorage',
          ValidationProgramId: '',
          Description: 'Drawing Storage',
          EntityDescription: 'Drawing Storage',
        },
        {
          Id: 'DrawingVersion',
          ConcurrencyToken: '5248052767796275222',
          Name: 'DrawingVersion',
          ValidationProgramId: '',
          Description: 'Drawing Version',
          EntityDescription: 'Drawing Version',
        },
        {
          Id: 'DuctRun',
          ConcurrencyToken: '5248052767796275222',
          Name: 'DuctRun',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Duct Run',
          EntityDescription: 'Duct Run',
        },
        {
          Id: 'DuctingComp',
          ConcurrencyToken: '5248052767796275222',
          Name: 'DuctingComp',
          ValidationProgramId: '',
          Description: 'Ducting Component',
          EntityDescription: 'Ducting Component',
        },
        {
          Id: 'DuctingPoint',
          ConcurrencyToken: '5248052767796275222',
          Name: 'DuctingPoint',
          ValidationProgramId: '',
          Description: 'Ducting Point',
          EntityDescription: 'Ducting Point',
        },
        {
          Id: 'EquipComponent',
          ConcurrencyToken: '5248052767796275222',
          Name: 'EquipComponent',
          ValidationProgramId: '',
          Description: 'Equipment: Component',
          EntityDescription: 'Equip Component',
        },
        {
          Id: 'Equipment',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Equipment',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Equipment',
          EntityDescription: 'Equipment',
        },
        {
          Id: 'EquipmentOther',
          ConcurrencyToken: '5248052767796275222',
          Name: 'EquipmentOther',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Equipment: Other',
          EntityDescription: 'Equipment Other',
        },
        {
          Id: 'Exchanger',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Exchanger',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Equipment: Heat Transfer',
          EntityDescription: 'Exchanger',
        },
        {
          Id: 'GlobalDrawing',
          ConcurrencyToken: '5248052767796275222',
          Name: 'GlobalDrawing',
          ValidationProgramId: '',
          Description: 'Global Drawing',
          EntityDescription: 'Global Drawing',
        },
        {
          Id: 'History',
          ConcurrencyToken: '5248052767796275222',
          Name: 'History',
          ValidationProgramId: '',
          Description: 'History',
          EntityDescription: 'History',
        },
        {
          Id: 'HydraulicCircuit',
          ConcurrencyToken: '5248052767796275222',
          Name: 'HydraulicCircuit',
          ValidationProgramId: '',
          Description: 'Hydraulic Circuit',
          EntityDescription: 'Hydraulic Circuit',
        },
        {
          Id: 'Inconsistency',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Inconsistency',
          ValidationProgramId: '',
          Description: 'Inconsistency',
          EntityDescription: 'Inconsistency',
        },
        {
          Id: 'InlineComp',
          ConcurrencyToken: '5248052767796275222',
          Name: 'InlineComp',
          ValidationProgramId: '',
          Description: 'Inline Component',
          EntityDescription: 'Inline Component',
        },
        {
          Id: 'InstrFailMode',
          ConcurrencyToken: '5248052767796275222',
          Name: 'InstrFailMode',
          ValidationProgramId: '',
          Description: 'Instrument Failure Mode',
          EntityDescription: 'Instrument Failure Mode',
        },
        {
          Id: 'InstrFunction',
          ConcurrencyToken: '5248052767796275222',
          Name: 'InstrFunction',
          ValidationProgramId: '',
          Description: 'Instrument Function',
          EntityDescription: 'Instrument Function',
        },
        {
          Id: 'InstrLoop',
          ConcurrencyToken: '5248052767796275222',
          Name: 'InstrLoop',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Instrument Loop',
          EntityDescription: 'Instrument Loop',
        },
        {
          Id: 'InstrOption',
          ConcurrencyToken: '5248052767796275222',
          Name: 'InstrOption',
          ValidationProgramId: '',
          Description: 'Instrument Option',
          EntityDescription: 'Instrument Option',
        },
        {
          Id: 'Instrument',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Instrument',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Instrument',
          EntityDescription: 'Instrument',
        },
        {
          Id: 'ItemNote',
          ConcurrencyToken: '5248052767796275222',
          Name: 'ItemNote',
          ValidationProgramId: '',
          Description: 'Item Note',
          EntityDescription: 'Item Note',
        },
        {
          Id: 'Label',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Label',
          ValidationProgramId: '',
          Description: 'Label: Catalog Item',
          EntityDescription: 'Label',
        },
        {
          Id: 'LabelPersist',
          ConcurrencyToken: '5248052767796275222',
          Name: 'LabelPersist',
          ValidationProgramId: '',
          Description: 'Label: Model Item',
          EntityDescription: 'Label Persist',
        },
        {
          Id: 'LeaderVertex',
          ConcurrencyToken: '5248052767796275222',
          Name: 'LeaderVertex',
          ValidationProgramId: '',
          Description: 'Leader Vertex',
          EntityDescription: 'Leader Vertex',
        },
        {
          Id: 'LlamaModification',
          ConcurrencyToken: '5248052767796275222',
          Name: 'LlamaModification',
          ValidationProgramId: '',
          Description: 'Llama Modification',
          EntityDescription: 'Llama Modification',
        },
        {
          Id: 'Location',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Location',
          ValidationProgramId: '',
          Description: 'Location',
          EntityDescription: 'Location',
        },
        {
          Id: 'Mechanical',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Mechanical',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Equipment: Mechanical',
          EntityDescription: 'Mechanical',
        },
        {
          Id: 'ModelItem',
          ConcurrencyToken: '5248052767796275222',
          Name: 'ModelItem',
          ValidationProgramId: '',
          Description: 'Model Item',
          EntityDescription: 'Model Item',
        },
        {
          Id: 'ModelItemClaim',
          ConcurrencyToken: '5248052767796275222',
          Name: 'ModelItemClaim',
          ValidationProgramId: '',
          Description: 'Model Item Claim',
          EntityDescription: 'Model Item Claim',
        },
        {
          Id: 'ModelItemClaimOffline',
          ConcurrencyToken: '5248052767796275222',
          Name: 'ModelItemClaimOffline',
          ValidationProgramId: '',
          Description: 'Model Item Claim Offline',
          EntityDescription: 'Model Item Claim Offline',
        },
        {
          Id: 'ModelItemClaimRep',
          ConcurrencyToken: '5248052767796275222',
          Name: 'ModelItemClaimRep',
          ValidationProgramId: '',
          Description: 'Model Item Claim Rep',
          EntityDescription: 'Model Item Claim Rep',
        },
        {
          Id: 'ModelItemLookup',
          ConcurrencyToken: '5248052767796275222',
          Name: 'ModelItemLookup',
          ValidationProgramId: '',
          Description: 'Model Item Lookup',
          EntityDescription: 'Model Item Lookup',
        },
        {
          Id: 'Note',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Note',
          ValidationProgramId: '',
          Description: 'Note',
          EntityDescription: 'Note',
        },
        {
          Id: 'Nozzle',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Nozzle',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Nozzle',
          EntityDescription: 'Nozzle',
        },
        {
          Id: 'OPC',
          ConcurrencyToken: '5248052767796275222',
          Name: 'OPC',
          ValidationProgramId: 'OPCValidate.SPForeignCalc',
          Description: 'OPC',
          EntityDescription: 'OPC',
        },
        {
          Id: 'OptionAutoGap',
          ConcurrencyToken: '5248052767796275222',
          Name: 'OptionAutoGap',
          ValidationProgramId: '',
          Description: 'Option Auto Gap',
          EntityDescription: 'Option Auto Gap',
        },
        {
          Id: 'OptionDispSet',
          ConcurrencyToken: '5248052767796275222',
          Name: 'OptionDispSet',
          ValidationProgramId: '',
          Description: 'Option Display Set',
          EntityDescription: 'Option Display Set',
        },
        {
          Id: 'OptionDispSetFolder',
          ConcurrencyToken: '5248052767796275222',
          Name: 'OptionDispSetFolder',
          ValidationProgramId: '',
          Description: 'Option Display Set Folder',
          EntityDescription: 'Option Display Set Folder',
        },
        {
          Id: 'OptionFormat',
          ConcurrencyToken: '5248052767796275222',
          Name: 'OptionFormat',
          ValidationProgramId: '',
          Description: 'Option Format',
          EntityDescription: 'Option Format',
        },
        {
          Id: 'OptionHeatTrace',
          ConcurrencyToken: '5248052767796275222',
          Name: 'OptionHeatTrace',
          ValidationProgramId: '',
          Description: 'Option Heat Trace',
          EntityDescription: 'Option Heat Trace',
        },
        {
          Id: 'OptionSetting',
          ConcurrencyToken: '5248052767796275222',
          Name: 'OptionSetting',
          ValidationProgramId: '',
          Description: 'Option Setting',
          EntityDescription: 'Option Setting',
        },
        {
          Id: 'OptionSymbology',
          ConcurrencyToken: '5248052767796275222',
          Name: 'OptionSymbology',
          ValidationProgramId: '',
          Description: 'Option Symbology',
          EntityDescription: 'Option Symbology',
        },
        {
          Id: 'Package',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Package',
          ValidationProgramId: '',
          Description: 'Package',
          EntityDescription: 'Package',
        },
        {
          Id: 'PipeRun',
          ConcurrencyToken: '5248052767796275222',
          Name: 'PipeRun',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Pipe Run',
          EntityDescription: 'Pipe Run',
        },
        {
          Id: 'Pipeline',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Pipeline',
          ValidationProgramId: '',
          Description: 'Pipeline',
          EntityDescription: 'Pipeline',
        },
        {
          Id: 'PipingComp',
          ConcurrencyToken: '5248052767796275222',
          Name: 'PipingComp',
          ValidationProgramId: '',
          Description: 'Piping Component',
          EntityDescription: 'Piping Component',
        },
        {
          Id: 'PipingPoint',
          ConcurrencyToken: '5248052767796275222',
          Name: 'PipingPoint',
          ValidationProgramId: '',
          Description: 'Piping Point',
          EntityDescription: 'Piping Point',
        },
        {
          Id: 'PlantItem',
          ConcurrencyToken: '5248052767796275222',
          Name: 'PlantItem',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Plant Item',
          EntityDescription: 'Plant Item',
        },
        {
          Id: 'PlantItemGroup',
          ConcurrencyToken: '5248052767796275222',
          Name: 'PlantItemGroup',
          ValidationProgramId: '',
          Description: 'Plant Item Group',
          EntityDescription: 'Plant Item Group',
        },
        {
          Id: 'PlantItemGroupJoin',
          ConcurrencyToken: '5248052767796275222',
          Name: 'PlantItemGroupJoin',
          ValidationProgramId: '',
          Description: 'Plant Item Group Join',
          EntityDescription: 'Plant Item Group Join',
        },
        {
          Id: 'PlantItemGroupOther',
          ConcurrencyToken: '5248052767796275222',
          Name: 'PlantItemGroupOther',
          ValidationProgramId: '',
          Description: 'Plant Item Group Other',
          EntityDescription: 'Plant Item Group Other',
        },
        {
          Id: 'PropertyBreak',
          ConcurrencyToken: '5248052767796275222',
          Name: 'PropertyBreak',
          ValidationProgramId: '',
          Description: 'Property Break',
          EntityDescription: 'Property Break',
        },
        {
          Id: 'Relationship',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Relationship',
          ValidationProgramId: '',
          Description: 'Relationship',
          EntityDescription: 'Relationship',
        },
        {
          Id: 'Representation',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Representation',
          ValidationProgramId: '',
          Description: 'Representation',
          EntityDescription: 'Representation',
        },
        {
          Id: 'RepresentationLookup',
          ConcurrencyToken: '5248052767796275222',
          Name: 'RepresentationLookup',
          ValidationProgramId: '',
          Description: 'Representation Lookup',
          EntityDescription: 'Representation Lookup',
        },
        {
          Id: 'Revision',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Revision',
          ValidationProgramId: 'ValidateDrawingRevision.ForeignCalc',
          Description: 'Revision',
          EntityDescription: 'Revision',
        },
        {
          Id: 'Room',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Room',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Room',
          EntityDescription: 'Room',
        },
        {
          Id: 'RoomComponent',
          ConcurrencyToken: '5248052767796275222',
          Name: 'RoomComponent',
          ValidationProgramId: '',
          Description: 'Room Component',
          EntityDescription: 'Room Component',
        },
        {
          Id: 'RuleReference',
          ConcurrencyToken: '5248052767796275222',
          Name: 'RuleReference',
          ValidationProgramId: '',
          Description: 'Rule Reference',
          EntityDescription: 'Rule Reference',
        },
        {
          Id: 'SafetyClass',
          ConcurrencyToken: '5248052767796275222',
          Name: 'SafetyClass',
          ValidationProgramId: '',
          Description: 'Safety Class',
          EntityDescription: 'Safety Class',
        },
        {
          Id: 'SignalPoint',
          ConcurrencyToken: '5248052767796275222',
          Name: 'SignalPoint',
          ValidationProgramId: '',
          Description: 'Signal Point',
          EntityDescription: 'Signal Point',
        },
        {
          Id: 'SignalRun',
          ConcurrencyToken: '5248052767796275222',
          Name: 'SignalRun',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Signal Run',
          EntityDescription: 'Signal Run',
        },
        {
          Id: 'SmartFrame',
          ConcurrencyToken: '5248052767796275222',
          Name: 'SmartFrame',
          ValidationProgramId: '',
          Description: 'Smart Frame',
          EntityDescription: 'Smart Frame',
        },
        {
          Id: 'SmartFrameStorage',
          ConcurrencyToken: '5248052767796275222',
          Name: 'SmartFrameStorage',
          ValidationProgramId: '',
          Description: 'Smart Frame Storage',
          EntityDescription: 'Smart Frame Storage',
        },
        {
          Id: 'Source',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Source',
          ValidationProgramId: '',
          Description: 'Source',
          EntityDescription: 'Source',
        },
        {
          Id: 'Status',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Status',
          ValidationProgramId: '',
          Description: 'Status',
          EntityDescription: 'Status',
        },
        {
          Id: 'Symbol',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Symbol',
          ValidationProgramId: '',
          Description: 'Symbol',
          EntityDescription: 'Symbol',
        },
        {
          Id: 'System',
          ConcurrencyToken: '5248052767796275222',
          Name: 'System',
          ValidationProgramId: '',
          Description: 'System',
          EntityDescription: 'System',
        },
        {
          Id: 'Task',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Task',
          ValidationProgramId: '',
          Description: 'Task',
          EntityDescription: 'Task',
        },
        {
          Id: 'TaskItemProperty',
          ConcurrencyToken: '5248052767796275222',
          Name: 'TaskItemProperty',
          ValidationProgramId: '',
          Description: 'Task Item Property',
          EntityDescription: 'Task Item Property',
        },
        {
          Id: 'Vessel',
          ConcurrencyToken: '5248052767796275222',
          Name: 'Vessel',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Equipment: Vessel',
          EntityDescription: 'Vessel',
        },
      ],
      'Items@odata.nextLink': "http://aisrvw10saas01/sem-webapi/Spem/V1/Sites('AGSite2018_1_Oracle')/Plants('AGPlant2018_2_Oracle')/Applications('Sppid')/Items?%24skip=81",
    },
    {
      Id: 'Sppe',
      ConcurrencyToken: '5248052767691743394',
      DataBaseType: 'Oracle',
      SiteIniFileNamePath: '\\\\ISRVSORA12SPEM\\AppOra12\\Alon Sites\\AGSite2018_1_Oracle',
      ApplicationType: 'Sppe',
      OracleAlias: 'SPEM12DEV',
      OracleSystemUser: 'system',
      OracleSystemPassword: 'H4#######5######R#######u#######d#######f#######o#######h#######',
      SchemaOracleUserName: 'AGPlant2018_2_Oraclepe',
      SchemaOraclePassword: 'BD3d#####J4f#####S;o#####obh#####d5s#####qbh#####wR######5u#####',
      DataDictOracleUserName: 'AGPlant2018_2_Oracleped',
      DataDictOraclePassword: 'BD3d#####J4f#####S;o#####obh#####d5s#####qbh#####wRg#####5u#####',
      'Items@odata.context': "http://aisrvw10saas01/sem-webapi/Spem/V1/$metadata#Sites('AGSite2018_1_Oracle')/Plants('AGPlant2018_2_Oracle')/Applications('Sppe')/Items",
      Items: [
        {
          Id: 'AreaBreak',
          ConcurrencyToken: '5248052767885494801',
          Name: 'AreaBreak',
          ValidationProgramId: '',
          Description: 'Area Break',
          EntityDescription: 'Area Break',
        },
        {
          Id: 'AreaBreakAttribute',
          ConcurrencyToken: '5248052767885494801',
          Name: 'AreaBreakAttribute',
          ValidationProgramId: '',
          Description: 'Area Break Attribute',
          EntityDescription: 'Area Break Attribute',
        },
        {
          Id: 'BoundedShape',
          ConcurrencyToken: '5248052767885494801',
          Name: 'BoundedShape',
          ValidationProgramId: '',
          Description: 'Bounded Shape',
          EntityDescription: 'Bounded Shape',
        },
        {
          Id: 'BoundedShapeVertex',
          ConcurrencyToken: '5248052767885494801',
          Name: 'BoundedShapeVertex',
          ValidationProgramId: '',
          Description: 'Bounded Shape Vertex',
          EntityDescription: 'Bounded Shape Vertex',
        },
        {
          Id: 'Case',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Case',
          ValidationProgramId: '',
          Description: 'Case',
          EntityDescription: 'Case',
        },
        {
          Id: 'CaseControl',
          ConcurrencyToken: '5248052767885494801',
          Name: 'CaseControl',
          ValidationProgramId: '',
          Description: 'Case Control',
          EntityDescription: 'Case Control',
        },
        {
          Id: 'CaseProcess',
          ConcurrencyToken: '5248052767885494801',
          Name: 'CaseProcess',
          ValidationProgramId: '',
          Description: 'Case Process',
          EntityDescription: 'Case Process',
        },
        {
          Id: 'Composition',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Composition',
          ValidationProgramId: '',
          Description: 'Composition',
          EntityDescription: 'Composition',
        },
        {
          Id: 'Connector',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Connector',
          ValidationProgramId: '',
          Description: 'Connector',
          EntityDescription: 'Connector',
        },
        {
          Id: 'ConnectorVertex',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ConnectorVertex',
          ValidationProgramId: '',
          Description: 'Connector Vertex',
          EntityDescription: 'Connector Vertex',
        },
        {
          Id: 'Drawing',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Drawing',
          ValidationProgramId: '',
          Description: 'Drawing',
          EntityDescription: 'Drawing',
        },
        {
          Id: 'DrawingProject',
          ConcurrencyToken: '5248052767885494801',
          Name: 'DrawingProject',
          ValidationProgramId: '',
          Description: 'Drawing Project',
          EntityDescription: 'Drawing Project',
        },
        {
          Id: 'DrawingStorage',
          ConcurrencyToken: '5248052767885494801',
          Name: 'DrawingStorage',
          ValidationProgramId: '',
          Description: 'Drawing Storage',
          EntityDescription: 'Drawing Storage',
        },
        {
          Id: 'DrawingVersion',
          ConcurrencyToken: '5248052767885494801',
          Name: 'DrawingVersion',
          ValidationProgramId: '',
          Description: 'Drawing Version',
          EntityDescription: 'Drawing Version',
        },
        {
          Id: 'DuctRun',
          ConcurrencyToken: '5248052767885494801',
          Name: 'DuctRun',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Duct Run',
          EntityDescription: 'Duct Run',
        },
        {
          Id: 'DuctingComp',
          ConcurrencyToken: '5248052767885494801',
          Name: 'DuctingComp',
          ValidationProgramId: '',
          Description: 'Ducting Component',
          EntityDescription: 'Ducting Component',
        },
        {
          Id: 'DuctingPoint',
          ConcurrencyToken: '5248052767885494801',
          Name: 'DuctingPoint',
          ValidationProgramId: '',
          Description: 'Ducting Point',
          EntityDescription: 'Ducting Point',
        },
        {
          Id: 'EquipComponent',
          ConcurrencyToken: '5248052767885494801',
          Name: 'EquipComponent',
          ValidationProgramId: '',
          Description: 'Equipment: Component',
          EntityDescription: 'Equip Component',
        },
        {
          Id: 'Equipment',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Equipment',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Equipment',
          EntityDescription: 'Equipment',
        },
        {
          Id: 'EquipmentOther',
          ConcurrencyToken: '5248052767885494801',
          Name: 'EquipmentOther',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Equipment: Other',
          EntityDescription: 'Equipment Other',
        },
        {
          Id: 'Exchanger',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Exchanger',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Equipment: Heat Transfer',
          EntityDescription: 'Exchanger',
        },
        {
          Id: 'GlobalDrawing',
          ConcurrencyToken: '5248052767885494801',
          Name: 'GlobalDrawing',
          ValidationProgramId: '',
          Description: 'Global Drawing',
          EntityDescription: 'Global Drawing',
        },
        {
          Id: 'History',
          ConcurrencyToken: '5248052767885494801',
          Name: 'History',
          ValidationProgramId: '',
          Description: 'History',
          EntityDescription: 'History',
        },
        {
          Id: 'HydraulicCircuit',
          ConcurrencyToken: '5248052767885494801',
          Name: 'HydraulicCircuit',
          ValidationProgramId: '',
          Description: 'Hydraulic Circuit',
          EntityDescription: 'Hydraulic Circuit',
        },
        {
          Id: 'Inconsistency',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Inconsistency',
          ValidationProgramId: '',
          Description: 'Inconsistency',
          EntityDescription: 'Inconsistency',
        },
        {
          Id: 'InlineComp',
          ConcurrencyToken: '5248052767885494801',
          Name: 'InlineComp',
          ValidationProgramId: '',
          Description: 'Inline Component',
          EntityDescription: 'Inline Component',
        },
        {
          Id: 'InstrFailMode',
          ConcurrencyToken: '5248052767885494801',
          Name: 'InstrFailMode',
          ValidationProgramId: '',
          Description: 'Instrument Failure Mode',
          EntityDescription: 'Instrument Failure Mode',
        },
        {
          Id: 'InstrFunction',
          ConcurrencyToken: '5248052767885494801',
          Name: 'InstrFunction',
          ValidationProgramId: '',
          Description: 'Instrument Function',
          EntityDescription: 'Instrument Function',
        },
        {
          Id: 'InstrLoop',
          ConcurrencyToken: '5248052767885494801',
          Name: 'InstrLoop',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Instrument Loop',
          EntityDescription: 'Instrument Loop',
        },
        {
          Id: 'InstrOption',
          ConcurrencyToken: '5248052767885494801',
          Name: 'InstrOption',
          ValidationProgramId: '',
          Description: 'Instrument Option',
          EntityDescription: 'Instrument Option',
        },
        {
          Id: 'Instrument',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Instrument',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Instrument',
          EntityDescription: 'Instrument',
        },
        {
          Id: 'ItemNote',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ItemNote',
          ValidationProgramId: '',
          Description: 'Item Note',
          EntityDescription: 'Item Note',
        },
        {
          Id: 'Label',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Label',
          ValidationProgramId: '',
          Description: 'Label: Catalog Item',
          EntityDescription: 'Label',
        },
        {
          Id: 'LabelPersist',
          ConcurrencyToken: '5248052767885494801',
          Name: 'LabelPersist',
          ValidationProgramId: '',
          Description: 'Label: Model Item',
          EntityDescription: 'Label Persist',
        },
        {
          Id: 'LeaderVertex',
          ConcurrencyToken: '5248052767885494801',
          Name: 'LeaderVertex',
          ValidationProgramId: '',
          Description: 'Leader Vertex',
          EntityDescription: 'Leader Vertex',
        },
        {
          Id: 'LlamaModification',
          ConcurrencyToken: '5248052767885494801',
          Name: 'LlamaModification',
          ValidationProgramId: '',
          Description: 'Llama Modification',
          EntityDescription: 'Llama Modification',
        },
        {
          Id: 'Location',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Location',
          ValidationProgramId: '',
          Description: 'Location',
          EntityDescription: 'Location',
        },
        {
          Id: 'Mechanical',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Mechanical',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Equipment: Mechanical',
          EntityDescription: 'Mechanical',
        },
        {
          Id: 'ModelItem',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ModelItem',
          ValidationProgramId: '',
          Description: 'Model Item',
          EntityDescription: 'Model Item',
        },
        {
          Id: 'ModelItemClaim',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ModelItemClaim',
          ValidationProgramId: '',
          Description: 'Model Item Claim',
          EntityDescription: 'Model Item Claim',
        },
        {
          Id: 'ModelItemClaimOffline',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ModelItemClaimOffline',
          ValidationProgramId: '',
          Description: 'Model Item Claim Offline',
          EntityDescription: 'Model Item Claim Offline',
        },
        {
          Id: 'ModelItemClaimRep',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ModelItemClaimRep',
          ValidationProgramId: '',
          Description: 'Model Item Claim Rep',
          EntityDescription: 'Model Item Claim Rep',
        },
        {
          Id: 'ModelItemLookup',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ModelItemLookup',
          ValidationProgramId: '',
          Description: 'Model Item Lookup',
          EntityDescription: 'Model Item Lookup',
        },
        {
          Id: 'Note',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Note',
          ValidationProgramId: '',
          Description: 'Note',
          EntityDescription: 'Note',
        },
        {
          Id: 'Nozzle',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Nozzle',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Nozzle',
          EntityDescription: 'Nozzle',
        },
        {
          Id: 'OPC',
          ConcurrencyToken: '5248052767885494801',
          Name: 'OPC',
          ValidationProgramId: 'OPCValidate.SPForeignCalc',
          Description: 'OPC',
          EntityDescription: 'OPC',
        },
        {
          Id: 'OptionAutoGap',
          ConcurrencyToken: '5248052767885494801',
          Name: 'OptionAutoGap',
          ValidationProgramId: '',
          Description: 'Option Auto Gap',
          EntityDescription: 'Option Auto Gap',
        },
        {
          Id: 'OptionDispSet',
          ConcurrencyToken: '5248052767885494801',
          Name: 'OptionDispSet',
          ValidationProgramId: '',
          Description: 'Option Display Set',
          EntityDescription: 'Option Display Set',
        },
        {
          Id: 'OptionDispSetFolder',
          ConcurrencyToken: '5248052767885494801',
          Name: 'OptionDispSetFolder',
          ValidationProgramId: '',
          Description: 'Option Display Set Folder',
          EntityDescription: 'Option Display Set Folder',
        },
        {
          Id: 'OptionFormat',
          ConcurrencyToken: '5248052767885494801',
          Name: 'OptionFormat',
          ValidationProgramId: '',
          Description: 'Option Format',
          EntityDescription: 'Option Format',
        },
        {
          Id: 'OptionHeatTrace',
          ConcurrencyToken: '5248052767885494801',
          Name: 'OptionHeatTrace',
          ValidationProgramId: '',
          Description: 'Option Heat Trace',
          EntityDescription: 'Option Heat Trace',
        },
        {
          Id: 'OptionSetting',
          ConcurrencyToken: '5248052767885494801',
          Name: 'OptionSetting',
          ValidationProgramId: '',
          Description: 'Option Setting',
          EntityDescription: 'Option Setting',
        },
        {
          Id: 'OptionSymbology',
          ConcurrencyToken: '5248052767885494801',
          Name: 'OptionSymbology',
          ValidationProgramId: '',
          Description: 'Option Symbology',
          EntityDescription: 'Option Symbology',
        },
        {
          Id: 'Package',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Package',
          ValidationProgramId: '',
          Description: 'Package',
          EntityDescription: 'Package',
        },
        {
          Id: 'PipeRun',
          ConcurrencyToken: '5248052767885494801',
          Name: 'PipeRun',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Pipe Run',
          EntityDescription: 'Pipe Run',
        },
        {
          Id: 'Pipeline',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Pipeline',
          ValidationProgramId: '',
          Description: 'Pipeline',
          EntityDescription: 'Pipeline',
        },
        {
          Id: 'PipingComp',
          ConcurrencyToken: '5248052767885494801',
          Name: 'PipingComp',
          ValidationProgramId: '',
          Description: 'Piping Component',
          EntityDescription: 'Piping Component',
        },
        {
          Id: 'PipingPoint',
          ConcurrencyToken: '5248052767885494801',
          Name: 'PipingPoint',
          ValidationProgramId: '',
          Description: 'Piping Point',
          EntityDescription: 'Piping Point',
        },
        {
          Id: 'PlantItem',
          ConcurrencyToken: '5248052767885494801',
          Name: 'PlantItem',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Plant Item',
          EntityDescription: 'Plant Item',
        },
        {
          Id: 'PlantItemGroup',
          ConcurrencyToken: '5248052767885494801',
          Name: 'PlantItemGroup',
          ValidationProgramId: '',
          Description: 'Plant Item Group',
          EntityDescription: 'Plant Item Group',
        },
        {
          Id: 'PlantItemGroupJoin',
          ConcurrencyToken: '5248052767885494801',
          Name: 'PlantItemGroupJoin',
          ValidationProgramId: '',
          Description: 'Plant Item Group Join',
          EntityDescription: 'Plant Item Group Join',
        },
        {
          Id: 'PlantItemGroupOther',
          ConcurrencyToken: '5248052767885494801',
          Name: 'PlantItemGroupOther',
          ValidationProgramId: '',
          Description: 'Plant Item Group Other',
          EntityDescription: 'Plant Item Group Other',
        },
        {
          Id: 'ProcComponentGroup',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ProcComponentGroup',
          ValidationProgramId: '',
          Description: 'Process Component Group',
          EntityDescription: 'Process Component Group',
        },
        {
          Id: 'ProcComponentGroupJoin',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ProcComponentGroupJoin',
          ValidationProgramId: '',
          Description: 'Process Component Group Join',
          EntityDescription: 'Process Component Group Join',
        },
        {
          Id: 'ProcComponentTemplate',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ProcComponentTemplate',
          ValidationProgramId: '',
          Description: 'Process Component Template',
          EntityDescription: 'Process Component Template',
        },
        {
          Id: 'ProcessComponent',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ProcessComponent',
          ValidationProgramId: '',
          Description: 'Process Component',
          EntityDescription: 'Process Component',
        },
        {
          Id: 'ProcessEngineeringCase',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ProcessEngineeringCase',
          ValidationProgramId: '',
          Description: 'Process Engineering Case',
          EntityDescription: 'Process Engineering Case',
        },
        {
          Id: 'ProcessPipeline',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ProcessPipeline',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Process Pipeline',
          EntityDescription: 'Process Pipeline',
        },
        {
          Id: 'ProcessPipelinePoint',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ProcessPipelinePoint',
          ValidationProgramId: '',
          Description: 'Process Pipeline Point',
          EntityDescription: 'Process Pipeline Point',
        },
        {
          Id: 'ProcessTechnology',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ProcessTechnology',
          ValidationProgramId: '',
          Description: 'Process Technology',
          EntityDescription: 'Process Technology',
        },
        {
          Id: 'ProcessTopology',
          ConcurrencyToken: '5248052767885494801',
          Name: 'ProcessTopology',
          ValidationProgramId: '',
          Description: 'Process Topology',
          EntityDescription: 'Process Topology',
        },
        {
          Id: 'PropertyBreak',
          ConcurrencyToken: '5248052767885494801',
          Name: 'PropertyBreak',
          ValidationProgramId: '',
          Description: 'Property Break',
          EntityDescription: 'Property Break',
        },
        {
          Id: 'Relationship',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Relationship',
          ValidationProgramId: '',
          Description: 'Relationship',
          EntityDescription: 'Relationship',
        },
        {
          Id: 'Representation',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Representation',
          ValidationProgramId: '',
          Description: 'Representation',
          EntityDescription: 'Representation',
        },
        {
          Id: 'RepresentationLookup',
          ConcurrencyToken: '5248052767885494801',
          Name: 'RepresentationLookup',
          ValidationProgramId: '',
          Description: 'Representation Lookup',
          EntityDescription: 'Representation Lookup',
        },
        {
          Id: 'Revision',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Revision',
          ValidationProgramId: 'ValidateDrawingRevision.ForeignCalc',
          Description: 'Revision',
          EntityDescription: 'Revision',
        },
        {
          Id: 'Room',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Room',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Room',
          EntityDescription: 'Room',
        },
        {
          Id: 'RoomComponent',
          ConcurrencyToken: '5248052767885494801',
          Name: 'RoomComponent',
          ValidationProgramId: '',
          Description: 'Room Component',
          EntityDescription: 'Room Component',
        },
        {
          Id: 'RuleReference',
          ConcurrencyToken: '5248052767885494801',
          Name: 'RuleReference',
          ValidationProgramId: '',
          Description: 'Rule Reference',
          EntityDescription: 'Rule Reference',
        },
        {
          Id: 'SafetyClass',
          ConcurrencyToken: '5248052767885494801',
          Name: 'SafetyClass',
          ValidationProgramId: '',
          Description: 'Safety Class',
          EntityDescription: 'Safety Class',
        },
        {
          Id: 'SignalPoint',
          ConcurrencyToken: '5248052767885494801',
          Name: 'SignalPoint',
          ValidationProgramId: '',
          Description: 'Signal Point',
          EntityDescription: 'Signal Point',
        },
        {
          Id: 'SignalRun',
          ConcurrencyToken: '5248052767885494801',
          Name: 'SignalRun',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Signal Run',
          EntityDescription: 'Signal Run',
        },
        {
          Id: 'SmartFrame',
          ConcurrencyToken: '5248052767885494801',
          Name: 'SmartFrame',
          ValidationProgramId: '',
          Description: 'Smart Frame',
          EntityDescription: 'Smart Frame',
        },
        {
          Id: 'SmartFrameStorage',
          ConcurrencyToken: '5248052767885494801',
          Name: 'SmartFrameStorage',
          ValidationProgramId: '',
          Description: 'Smart Frame Storage',
          EntityDescription: 'Smart Frame Storage',
        },
        {
          Id: 'Source',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Source',
          ValidationProgramId: '',
          Description: 'Source',
          EntityDescription: 'Source',
        },
        {
          Id: 'Status',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Status',
          ValidationProgramId: '',
          Description: 'Status',
          EntityDescription: 'Status',
        },
        {
          Id: 'Stream',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Stream',
          ValidationProgramId: '',
          Description: 'Stream',
          EntityDescription: 'Stream',
        },
        {
          Id: 'Symbol',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Symbol',
          ValidationProgramId: '',
          Description: 'Symbol',
          EntityDescription: 'Symbol',
        },
        {
          Id: 'System',
          ConcurrencyToken: '5248052767885494801',
          Name: 'System',
          ValidationProgramId: '',
          Description: 'System',
          EntityDescription: 'System',
        },
        {
          Id: 'Task',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Task',
          ValidationProgramId: '',
          Description: 'Task',
          EntityDescription: 'Task',
        },
        {
          Id: 'TaskItemProperty',
          ConcurrencyToken: '5248052767885494801',
          Name: 'TaskItemProperty',
          ValidationProgramId: '',
          Description: 'Task Item Property',
          EntityDescription: 'Task Item Property',
        },
        {
          Id: 'UOP',
          ConcurrencyToken: '5248052767885494801',
          Name: 'UOP',
          ValidationProgramId: '',
          Description: 'Unit Operation',
          EntityDescription: 'Unit Operation',
        },
        {
          Id: 'UOPExchanger',
          ConcurrencyToken: '5248052767885494801',
          Name: 'UOPExchanger',
          ValidationProgramId: '',
          Description: 'Unit Operation Exchanger',
          EntityDescription: 'Unit Operation Exchanger',
        },
        {
          Id: 'UOPMechanical',
          ConcurrencyToken: '5248052767885494801',
          Name: 'UOPMechanical',
          ValidationProgramId: '',
          Description: 'Unit Operation Mechanical',
          EntityDescription: 'Unit Operation Mechanical',
        },
        {
          Id: 'UOPOther',
          ConcurrencyToken: '5248052767885494801',
          Name: 'UOPOther',
          ValidationProgramId: '',
          Description: 'Unit Operation Other',
          EntityDescription: 'Unit Operation Other',
        },
        {
          Id: 'UOPVessel',
          ConcurrencyToken: '5248052767885494801',
          Name: 'UOPVessel',
          ValidationProgramId: '',
          Description: 'Unit Operation Vessel',
          EntityDescription: 'Unit Operation Vessel',
        },
        {
          Id: 'Vessel',
          ConcurrencyToken: '5248052767885494801',
          Name: 'Vessel',
          ValidationProgramId: 'PlantItemValidation.Validate',
          Description: 'Equipment: Vessel',
          EntityDescription: 'Vessel',
        },
      ],
      'Items@odata.nextLink': "http://aisrvw10saas01/sem-webapi/Spem/V1/Sites('AGSite2018_1_Oracle')/Plants('AGPlant2018_2_Oracle')/Applications('Sppe')/Items?%24skip=97",
    },
  ],
};
