import theme from '../../themes/light';

const backgroundColors: string[] = [
  theme.palette.hexagon.purple[1],
  theme.palette.hexagon.purple[2],
  theme.palette.hexagon.indigo[1],
  theme.palette.hexagon.indigo[2],
  theme.palette.hexagon.blue[1],
  theme.palette.hexagon.blue[2],
  theme.palette.hexagon.deepBlue[1],
  theme.palette.hexagon.deepBlue[2],
  theme.palette.hexagon.inkBlue[1],
  theme.palette.hexagon.inkBlue[2],
  theme.palette.hexagon.ceruleanBlue[1],
  theme.palette.hexagon.ceruleanBlue[2],
  theme.palette.hexagon.darkCeruleanBlue[1],
  theme.palette.hexagon.darkCeruleanBlue[2],
  theme.palette.hexagon.blueLagoon[1],
  theme.palette.hexagon.blueLagoon[2],
  theme.palette.hexagon.mediumCeruleanBlue[1],
  theme.palette.hexagon.mediumCeruleanBlue[2],
  theme.palette.hexagon.cyan[1],
  theme.palette.hexagon.cyan[2],
  theme.palette.hexagon.deepCyan[1],
  theme.palette.hexagon.deepCyan[2],
  theme.palette.hexagon.deepTeal[1],
  theme.palette.hexagon.deepTeal[2],
  theme.palette.hexagon.watercourse[1],
  theme.palette.hexagon.watercourse[2],
  theme.palette.hexagon.deepGreen[1],
  theme.palette.hexagon.deepGreen[2],
  theme.palette.hexagon.shamrockGreen[1],
  theme.palette.hexagon.shamrockGreen[2],
  theme.palette.hexagon.pigmentGreen[1],
  theme.palette.hexagon.pigmentGreen[2],
  theme.palette.hexagon.lightGreen[1],
  theme.palette.hexagon.lightGreen[2],
  theme.palette.hexagon.yellowGreen[1],
  theme.palette.hexagon.yellowGreen[2],
  theme.palette.hexagon.lime[1],
  theme.palette.hexagon.lime[2],
  theme.palette.hexagon.orange[1],
  theme.palette.hexagon.orange[2],
  theme.palette.hexagon.deepOrange[1],
  theme.palette.hexagon.deepOrange[2],
  theme.palette.hexagon.tenneOrange[1],
  theme.palette.hexagon.tenneOrange[2],
  theme.palette.hexagon.rust[1],
  theme.palette.hexagon.rust[2],
  theme.palette.hexagon.reddishBrown[1],
  theme.palette.hexagon.reddishBrown[2],
  theme.palette.hexagon.brown[1],
  theme.palette.hexagon.brown[2],
  theme.palette.hexagon.darkRed[1],
  theme.palette.hexagon.darkRed[2],
  theme.palette.hexagon.raven[1],
  theme.palette.hexagon.raven[2],
  theme.palette.hexagon.deepGray[1],
  theme.palette.hexagon.deepGray[2],
];

export default function getColorCodes(): string {
  return backgroundColors[Math.floor(Math.random() * backgroundColors.length)];
}
